FROM python:3.13.7-slim

WORKDIR /app

# Install required packages
RUN pip install --no-cache-dir \
    catboost==1.2.8 \
    mlflow==2.22.0 \
    colorama==0.4.6 \
    ipython==9.1.0 \
    scipy==1.16.1 \
    fastapi \
    uvicorn[standard] \
    pandas \
    boto3

COPY inference_app /app

RUN chmod +x entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]