[project]
name = "pred-maint"
version = "0.1.0"
description = "Predictive Maintenance Engineering Challenge"
readme = "README.MD"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.37.10",
    "catboost>=1.2.8",
    "fastapi>=0.116.1",
    "hyperopt>=0.2.7",
    "kagglehub>=0.2.7",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.6",
    "mlflow>=2.22.0",
    "mplcyberpunk==0.7.6",
    "mypy>=2.1.0",
    "pandas>=2.3.2",
    "prefect>=3.4.19",
    "pydantic>=2.11.7",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.1.0",
    "ruff>=0.15.16",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.1",
    "seaborn>=0.13.2",
    "uvicorn>=0.35.0",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]  # Ignore line length for now as notebooks have many long lines

[tool.ruff.lint.isort]
known-first-party = ["app", "inference_app"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--cov=app --cov=inference_app --cov-report=term-missing"

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true
